#cloud-config
users:
  - name: demo
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkQN3ZiNFqalUyTagMCD4BxnflyXd+5+5QFlPay9locW4qt2YpxFgdzmwoJ0qkIKa959nv/qrvMX1HXmP9ZyxGAQUbGTWHGp3BaS+QTWGD84QAoyAo+k9yF+VqPqHZFYpj0eeT/gMY7JBR8KWe1TxErRgv0AP7mohraF8M7eP9R3C3RIGhG1A22C5NcRQ5FYvzO6WzJJndvg0QVvHcUtFkG3k6PjvJZJoWFCQ3JYYlNlFB3yejOnO/sd8iDa+NAPMs7V4bL3P9UQ2B4LMo3KVi0oYqkLay3GHhcptU4my4EYZ9Z+x2kcKgRLgsLvIkxjvOvnDfoiiBn7vYyr+sAy9KACZkn3safd6zfwreySC+YS4AWn3mTQXjrXgLJVn+Atqjg95v+Fm6aJXkpzrQoQF8GjmF2iMArikoMV/rvZ0cDdxDyKPw4oHHh/BTcTWhDJUpLJ0ibdmzlbiznkngj2YSJessmh1TpYkuyiVadIH8K8Cp/UHZGO87KQltvAcBmhXBJVE1H4AAc/vaFQLNImnzCi53cBsFQD05x3i9C2egSCQmOnSHbAwwTy8tpIseB5h+W1KCH2Pn4e47FhAHbTwQp6ym1NXrZsajvgdROxSJQHuO8NFy1+llGSDd2mfM/PO66fRFk1cOPkq9Q7sK+sD8IANOVKgElvow7LtJzzIJDw== nurlan@Nurlans-MacBook-Pro.local
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
write_files:
  - path: /etc/ssh/sshd_config
    content: |
         Port 4444
         Protocol 2
         HostKey /etc/ssh/ssh_host_rsa_key
         HostKey /etc/ssh/ssh_host_dsa_key
         HostKey /etc/ssh/ssh_host_ecdsa_key
         HostKey /etc/ssh/ssh_host_ed25519_key
         UsePrivilegeSeparation yes
         KeyRegenerationInterval 3600
         ServerKeyBits 1024
         SyslogFacility AUTH
         LogLevel INFO
         LoginGraceTime 120
         PermitRootLogin yes
         StrictModes yes
         RSAAuthentication yes
         PubkeyAuthentication yes
         IgnoreRhosts yes
         RhostsRSAAuthentication no
         HostbasedAuthentication no
         PermitEmptyPasswords no
         ChallengeResponseAuthentication no
         X11Forwarding yes
         X11DisplayOffset 10
         PrintMotd no
         PrintLastLog yes
         TCPKeepAlive yes
         AcceptEnv LANG LC_*
         Subsystem sftp /usr/lib/openssh/sftp-server
         UsePAM yes
         AllowUsers demo